### PR TITLE
Team's Page

### PR DESCRIPTION
**Pull request by pwhited-7**
Added Gwyn's headshot and bio

### CODE REVIEW

**Comment by Shizcow** [comment]
@pwhited-7 Gwyn is a junior, not a senior. Can you propose this PR again? I stupidly merged it before taking a look and had to revert.

**Comment by Shizcow** [comment]
Actually, I can just do the changes manually.

**Comment by pwhited-7** [comment]
Okay thank you, sorry about that. Let me know if I need to make changes and do the PR again.

**Comment by Shizcow** [comment]
Nah it's all good I changed it. My bad for making the mistake in the first place.

**Pull request merged**
